name: The Brotherhood of Olympus
favicon: null
layout_spectrum: 0.82611
typography_spectrum: 0.75181
title: 'Official Website of Best Selling Author and Award Winning Illustrator, Guy T. Simpson, Jr.'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#3bd1f6'
    - '#113f48'
    - '#2d7d8f'
    - '#409eb6'
  brandStrength: 0.25
  lightness: 0.4375
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
